name: Docker Image CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to GitHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }}  --password-stdin
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: docker.pkg.github.com/vergissberlin/andrelademann-de/app
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
    
